### ISSUE TITLE
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="config()"

### ISSUE THREAD

**Issue by AnthonyMadia** [VGLoic/eth-testing#55]
### Open

Hello 👋🏻, 

I am very excited to use this tool but I need some help understanding where it can help me. 

I am testing a method on a class that throws an ethers error, but I am unsure how to mock this out using your library. 

The total error is: 
```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="config()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.Object.<anonymous>.Logger.makeError (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.Object.<anonymous>.Logger.throwError (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Interface.Object.<anonymous>.Interface.decodeFunctionResult (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
    at Contract.<anonymous> (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at step (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'config()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x0000000000000000000000000000000000000000',
  args: [],
  transaction: {
    data: '0x79502c55',
    to: '0x0000000000000000000000000000000000000000'
  }
}
```

I imported the library to generate the testing contract utils because I think from the error above I have to find a way to mock the `config()` method. Not 100% sure though. 

Below you can see the test that is throwing the error which is (probably naively) trying to mock the config method with `contractTestingUtils.mockCall('config')`.

Here's how I mocked it:
```js
import { generateTestingUtils } from 'eth-testing'

const testingUtils = generateTestingUtils({
    providerType: config.DEFAULT_ETH_PROVIDER,
})
const contractTestingUtils = testingUtils.generateContractUtils(
    config.UNIREP_ABI,
    config.UNIREP_SOCIAL_ABI
)

test('save() calls setItem on localStorage', async () => {
        const windowSetItemSpy = jest.spyOn(localStorage, 'setItem')
        // no identity set, so will not be called
        user.save()
        expect(windowSetItemSpy).not.toHaveBeenCalled()
        // now create identity, and then call save()
        user.id = new ZkIdentity()
        contractTestingUtils.mockCall('config') // contract testing utils method!!!!!!!
        user.save()
        expect(windowSetItemSpy).toHaveBeenCalled()
    })
```
I won't post all the code here because it will be too verbose, but hopefully, this is enough for a push in the right direction. Thanks.

**Comment by VGLoic** [comment]
Hey @AnthonyMadia !

Thanks a lot for this issue :)

Just to be sure to correctly understand, the goal is to mock the `config` method in order to resolve to something or to intentionally throw on call? :)

If we want to resolve to some data, we will need to do something as
```typescript
const configData = [1, 'hello']; // random stuff here as I don't know what config return type is
contractTestingUtils.mockCall('config', configData)
```

If we want it to intentionally throw, we can do something like
```typescript
const myError = new Error('bla');
contractTestingUtils.mockCall('config', myError, undefined, { shouldThrow: true });
```

Please don't hesitate to share with me any repo or else in order that I can better help you :)

Also, in your snippet, you have 
```typescript
const contractTestingUtils = testingUtils.generateContractUtils(
    config.UNIREP_ABI,
    config.UNIREP_SOCIAL_ABI
)
```
which is a bit surprising as the second argument of `generateContractUtils` should be the address of the contract and not an abi 🤔

**Comment by AnthonyMadia** [comment]
Thanks for the response! 

After trying the mock, I am getting a a type/values length mismatch error:

```
types/values length mismatch (count={"types":10}, value={"types":[{"name":"globalStateTreeDepth","type":"uint8","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint8","_isParamType":true},{"name":"userStateTreeDepth","type":"uint8","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint8","_isParamType":true},{"name":"epochTreeDepth","type":"uint8","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint8","_isParamType":true},{"name":"numEpochKeyNoncePerEpoch","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"maxReputationBudget","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"numAttestationsPerProof","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"epochLength","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"attestingFee","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"maxUsers","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"maxAttesters","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true}],"values":true}, code=INVALID_ARGUMENT, version=abi/5.7.0)

      41 |         user.id = new ZkIdentity()
      42 |         const configData = true
    > 43 |         contractTestingUtils.mockCall('config', configData)
         |                              ^
      44 |         user.save()
      45 |         expect(windowSetItemSpy).toHaveBeenCalled()
      46 |     })

      at Logger.Object.<anonymous>.Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.Object.<anonymous>.Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at AbiCoder.Object.<anonymous>.AbiCoder.encode (node_modules/@ethersproject/abi/src.ts/abi-coder.ts:101:20)
      at Interface.Object.<anonymous>.Interface.encodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:439:39)
      at ContractUtils.Object.<anonymous>.ContractUtils.mockCall (node_modules/eth-testing/lib/testing-utils/contract-utils.js:72:49)
      at Object.mockCall (src/__tests__/user.js:43:30)
```
I have googled and found [this](https://stackoverflow.com/questions/56944299/how-to-fix-error-types-values-length-mismatch-in-contract-testing) StackOverflow. 

If I believe what the StackOverflow post is saying then I need some way to mock the constructor of the Unirep contract which can be found here: https://github.com/Unirep/Unirep/blob/main/packages/contracts/contracts/Unirep.sol#:~:text=constructor(,%7D). I am not entirely sure how to mock this constructor or if this is what is causing the problem.

**Comment by VGLoic** [comment]
Ooh I see, could you try with the exact data from config? Following the struct
```solidity
struct Config {
        // circuit config
        uint8 globalStateTreeDepth;
        uint8 userStateTreeDepth;
        uint8 epochTreeDepth;
        uint256 numEpochKeyNoncePerEpoch;
        uint256 maxReputationBudget;
        uint256 numAttestationsPerProof;
        // contract config
        uint256 epochLength;
        uint256 attestingFee;
        uint256 maxUsers;
        uint256 maxAttesters;
    }
```
So in the test it would look like
```typescript
const configData = {
 globalStateTreeDepth: "0x0",
 userStateTreeDepth: "0x0",
 epochTreeDepth: "0x0",
 numEpochKeyNoncePerEpoch: "0x0",
 maxReputationBudget: "0x0",
 numAttestationsPerProof: "0x0",
 epochLength: "0x0",
 attestingFee: "0x0",
 maxUsers: "0x0",
 maxAttesters: "0x0",
}
contractTestingUtils.mockCall('config', configData)
```

**Comment by AnthonyMadia** [comment]
Darn I still get the same error using that test.


```
    types/values length mismatch (count={"types":10}, value={"types":[{"name":"globalStateTreeDepth","type":"uint8","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint8","_isParamType":true},{"name":"userStateTreeDepth","type":"uint8","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint8","_isParamType":true},{"name":"epochTreeDepth","type":"uint8","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint8","_isParamType":true},{"name":"numEpochKeyNoncePerEpoch","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"maxReputationBudget","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"numAttestationsPerProof","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"epochLength","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"attestingFee","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"maxUsers","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true},{"name":"maxAttesters","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true}],"values":{"globalStateTreeDepth":"0x0","userStateTreeDepth":"0x0","epochTreeDepth":"0x0","numEpochKeyNoncePerEpoch":"0x0","maxReputationBudget":"0x0","numAttestationsPerProof":"0x0","epochLength":"0x0","attestingFee":"0x0","maxUsers":"0x0","maxAttesters":"0x0"}}, code=INVALID_ARGUMENT, version=abi/5.7.0)

      52 |             maxAttesters: '0x0',
      53 |         }
    > 54 |         contractTestingUtils.mockCall('config', configData)
         |                              ^
      55 |         user.save()
      56 |         expect(windowSetItemSpy).toHaveBeenCalled()
      57 |     })

      at Logger.Object.<anonymous>.Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.Object.<anonymous>.Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at AbiCoder.Object.<anonymous>.AbiCoder.encode (node_modules/@ethersproject/abi/src.ts/abi-coder.ts:101:20)
      at Interface.Object.<anonymous>.Interface.encodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:439:39)
      at ContractUtils.Object.<anonymous>.ContractUtils.mockCall (node_modules/eth-testing/lib/testing-utils/contract-utils.js:72:49)
      at Object.mockCall (src/__tests__/user.js:54:30)
```

**Comment by VGLoic** [comment]
Oh my bad sorry, we need to wrap it using an array 🤦 

```typescript
// Changed at needs
const configData = {
 globalStateTreeDepth: "0x0",
 userStateTreeDepth: "0x0",
 epochTreeDepth: "0x0",
 numEpochKeyNoncePerEpoch: "0x0",
 maxReputationBudget: "0x0",
 numAttestationsPerProof: "0x0",
 epochLength: "0x0",
 attestingFee: "0x0",
 maxUsers: "0x0",
 maxAttesters: "0x0",
}
contractTestingUtils.mockCall('config', [configData])
```

I need to stop here but I will go back to you tomorrow 😁

**Comment by AnthonyMadia** [comment]
Yea no worries. I'm still getting the same error, but I am just going to keep playing around with it

**Comment by VGLoic** [comment]
So as I understand, `config` is a public getter on a struct, so the JSON-RPC call does not give an object but simply the values of the struct as an array

What it means is that the correct mocking would be of the form
```typescript
unirepTestingUtils.mockCall("config", [
      0, // globalStateTreeDepth
      0, // userStateTreeDepth
      0, // epochTreeDepth
      10, // numEpochKeyNoncePerEpoch
      10, // maxReputationBudget
      10, // numAttestationsPerProof
      10, // epochLength
      10, // attestingFee
      10, // maxUsers
      10, // maxAttesters
    ]);
```

If the test contains multiple calls to the method, you may want to write it as
```typescript
unirepTestingUtils.mockCall("config", [
      0, // globalStateTreeDepth
      0, // userStateTreeDepth
      0, // epochTreeDepth
      10, // numEpochKeyNoncePerEpoch
      10, // maxReputationBudget
      10, // numAttestationsPerProof
      10, // epochLength
      10, // attestingFee
      10, // maxUsers
      10, // maxAttesters
    ], undefined, { persistent: true });
```
The `persistent: true` will persist the mock :)

I got a successful test running on my side (it's quite messy but I will try to have a ready to be shown codesandbox at some point 😅 )

Please tell me how it goes on your side :)

**Comment by AnthonyMadia** [comment]
Trying this now. 
> I got a successful test running on my side (it's quite messy but I will try to have a ready to be shown codesandbox at some point 

Do you mean that you ran [this](https://github.com/VGLoic/eth-testing/issues/55#:~:text=test(%27save,)%0A%20%20%20%20%7D) test with the unirepTestingUtils mock call?

I just tried using both of the unirepTestingUtils you mentioned. The tests pass but the error is being thrown after the tests pass:

```
Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        2.111 s
Ran all test suites matching /src\/__tests__\/user.js/i.
/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="config()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.Object.<anonymous>.Logger.makeError (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.Object.<anonymous>.Logger.throwError (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Interface.Object.<anonymous>.Interface.decodeFunctionResult (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
    at Contract.<anonymous> (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at step (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/home/anthonymadia/Code/Work/Unirep-Social/packages/frontend/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'config()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x0000000000000000000000000000000000000000',
  args: [],
  transaction: {
    data: '0x79502c55',
    to: '0x0000000000000000000000000000000000000000'
  }
}
```

**Comment by VGLoic** [comment]
No I have done a test on my side with a single call on `methods` triggered from a React component!

Hmm interesting, even with the `persistent: true` option? 

Do you have a link to your test? I would need to understand a bit better when this `config` method is triggered if possible :)

**Comment by AnthonyMadia** [comment]
If you have time, you can clone down this repo, run `yarn && yarn build`, and checkout to [this](https://github.com/Unirep/Unirep-Social/pull/148) PR. Then cd into packages/frontend and run `yarn test src/__tests__/user.js`.  

And yes, I tried with the `persistent: true` option. 

Here is a [link](https://github.com/Unirep/Unirep-Social/pull/148/files#:~:text=test(%27save()%20calls%20setItem,).toHaveBeenCalled()) to the test.

**Comment by AnthonyMadia** [comment]
I'm also still not entirely sure the library will help me here because if you comment out all the eth-testing stuff, then the same error will appear.

**Comment by VGLoic** [comment]
Okay I understand a bit better now!

So indeed, adding the library is doing nothing in the current state 😁 

The goal is to generate a mock Web3 provider and inject it in our app instead of the "official" one. However, in the case of Unirep Social, the web3 provider is actually initialized in `src/config.ts` and then used across the app. 

So when we are initializing the mock provider in the test, or putting it in the window, it is actually not used hehe.

The sad news is that it would require quite a number of changes in the app in order to use the testing utils here :(

Ideally the `User` class or the `UnirepConfig` class should take the provider in argument (and potentially fallback to this static default one) but it would require quite a number of changes :(

Does that make sense to you? :)

**Comment by AnthonyMadia** [comment]
> So when we are initializing the mock provider in the test, or putting it in the window, it is actually not used hehe. 
Ah that makes sense. 

>The sad news is that it would require quite a number of changes in the app in order to use the testing utils here :(
Darn, what would the changes be though?

And I'm not exactly sure why the classes should take the provider in thee argument.

**Comment by VGLoic** [comment]
I think that in order to have clean tests, dependencies should be more explicit

What I mean by that is that the `User` class implicitly depends on the `UnirepContext`. The `UnirepContext` itself implicitly depends on `SERVER` and `DEFAULT_ETH_PROVIDER`.

It works very well, however this kind of code is quite hard to test (and harder to understand too) in my opinion. Let's say we want to test the `UnirepConfig` underneath the `UnirepContext`, since it depends on constants `SERVER` or `DEFAULT_ETH_PROVIDER`, it will be very hard to test it with a mock server and a mock eth provider (which we want in the tests because otherwise we are triggering real server call or real JSON RPC calls).

However, if we make the dependencies more explicit, such as `const unirepConfig = new UnirepConfig(server, provider)`, then we can differentiate the arguments whether it is used in the development, production, testing or else.

Same goes with `User` which depends on the context, and could be defined as `const user = new User(unirepContext)` where `unirepContext` is defined with the dependencies you chose.

Of course all of that is quite theoretical, I don't really know the app and it is mostly my opinion 🙈

You could potentially forcing the injection of a mock provider in the current state by modifying directly the `config.ts` file but I think it's quite dangerous
```typescript
const testingUtils = generateTestingUtils();

const DEFAULT_ETH_PROVIDER = process.env.NODE_ENV === 'test'
    ? new ethers.providers.Web3Provider(testingUtils.getProvider())
    : DEFAULT_ETH_PROVIDER_URL.startsWith('http')
    ? new ethers.providers.JsonRpcProvider(DEFAULT_ETH_PROVIDER_URL)
    : new ethers.providers.WebSocketProvider(DEFAULT_ETH_PROVIDER_URL)
```
